/*
 * Alumni Platform - User Service API
 * API du service de gestion des utilisateurs.  Ce service gère les profils utilisateurs de la plateforme Alumni. L'authentification et les autorisations sont déléguées à Keycloak.  Les utilisateurs peuvent être : - ADMIN - TEACHER - STUDENT - ALUMNI 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Address
 */
class AddressTest {
    private final Address model = new Address();

    /**
     * Model tests for Address
     */
    @Test
    void testAddress() {
        // TODO: test Address
    }

    /**
     * Test the property 'country'
     */
    @Test
    void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'city'
     */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'street'
     */
    @Test
    void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    void postalCodeTest() {
        // TODO: test postalCode
    }

}
