/*
 * Alumni Platform - User Service API
 * API du service de gestion des utilisateurs.  Ce service gère les profils utilisateurs de la plateforme Alumni. L'authentification et les autorisations sont déléguées à Keycloak.  Les utilisateurs peuvent être : - ADMIN - TEACHER - STUDENT - ALUMNI 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserPage
 */
class UserPageTest {
    private final UserPage model = new UserPage();

    /**
     * Model tests for UserPage
     */
    @Test
    void testUserPage() {
        // TODO: test UserPage
    }

    /**
     * Test the property 'content'
     */
    @Test
    void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'page'
     */
    @Test
    void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'size'
     */
    @Test
    void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'totalElements'
     */
    @Test
    void totalElementsTest() {
        // TODO: test totalElements
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    void totalPagesTest() {
        // TODO: test totalPages
    }

    /**
     * Test the property 'hasNext'
     */
    @Test
    void hasNextTest() {
        // TODO: test hasNext
    }

    /**
     * Test the property 'hasPrevious'
     */
    @Test
    void hasPreviousTest() {
        // TODO: test hasPrevious
    }

}
