/*
 * Alumni Platform - User Service API
 * API du service de gestion des utilisateurs.  Ce service gère les profils utilisateurs de la plateforme Alumni. L'authentification et les autorisations sont déléguées à Keycloak.  Les utilisateurs peuvent être : - ADMIN - TEACHER - STUDENT - ALUMNI 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.UserType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CreateUserRequest
 */
@JsonPropertyOrder({
  CreateUserRequest.JSON_PROPERTY_KEYCLOAK_ID,
  CreateUserRequest.JSON_PROPERTY_EMAIL,
  CreateUserRequest.JSON_PROPERTY_FIRST_NAME,
  CreateUserRequest.JSON_PROPERTY_LAST_NAME,
  CreateUserRequest.JSON_PROPERTY_PHONE,
  CreateUserRequest.JSON_PROPERTY_TYPE,
  CreateUserRequest.JSON_PROPERTY_ADDRESS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-30T10:49:02.701015900Z[Africa/Sao_Tome]", comments = "Generator version: 7.24.0")
public class CreateUserRequest {
  public static final String JSON_PROPERTY_KEYCLOAK_ID = "keycloakId";
  @javax.annotation.Nonnull
  private String keycloakId;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nonnull
  private String email;

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  @javax.annotation.Nonnull
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  @javax.annotation.Nonnull
  private String lastName;

  public static final String JSON_PROPERTY_PHONE = "phone";
  @javax.annotation.Nullable
  private String phone;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private UserType type;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private Address address;

  public CreateUserRequest() {
  }

  public CreateUserRequest keycloakId(@javax.annotation.Nonnull String keycloakId) {
    
    this.keycloakId = keycloakId;
    return this;
  }

  /**
   * Get keycloakId
   * @return keycloakId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEYCLOAK_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKeycloakId() {
    return keycloakId;
  }


  @JsonProperty(value = JSON_PROPERTY_KEYCLOAK_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeycloakId(@javax.annotation.Nonnull String keycloakId) {
    this.keycloakId = keycloakId;
  }

  public CreateUserRequest email(@javax.annotation.Nonnull String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
  }

  public CreateUserRequest firstName(@javax.annotation.Nonnull String firstName) {
    
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstName(@javax.annotation.Nonnull String firstName) {
    this.firstName = firstName;
  }

  public CreateUserRequest lastName(@javax.annotation.Nonnull String lastName) {
    
    this.lastName = lastName;
    return this;
  }

  /**
   * Get lastName
   * @return lastName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastName(@javax.annotation.Nonnull String lastName) {
    this.lastName = lastName;
  }

  public CreateUserRequest phone(@javax.annotation.Nullable String phone) {
    
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }

  public CreateUserRequest type(@javax.annotation.Nullable UserType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable UserType type) {
    this.type = type;
  }

  public CreateUserRequest address(@javax.annotation.Nullable Address address) {
    
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Address getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable Address address) {
    this.address = address;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateUserRequest createUserRequest = (CreateUserRequest) o;
    return Objects.equals(this.keycloakId, createUserRequest.keycloakId) &&
        Objects.equals(this.email, createUserRequest.email) &&
        Objects.equals(this.firstName, createUserRequest.firstName) &&
        Objects.equals(this.lastName, createUserRequest.lastName) &&
        Objects.equals(this.phone, createUserRequest.phone) &&
        Objects.equals(this.type, createUserRequest.type) &&
        Objects.equals(this.address, createUserRequest.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keycloakId, email, firstName, lastName, phone, type, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateUserRequest {\n");
    sb.append("    keycloakId: ").append(toIndentedString(keycloakId)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

