/*
 * Alumni Platform - User Service API
 * API du service de gestion des utilisateurs.  Ce service gère les profils utilisateurs de la plateforme Alumni. L'authentification et les autorisations sont déléguées à Keycloak.  Les utilisateurs peuvent être : - ADMIN - TEACHER - STUDENT - ALUMNI 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.User;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * UserPage
 */
@JsonPropertyOrder({
  UserPage.JSON_PROPERTY_CONTENT,
  UserPage.JSON_PROPERTY_PAGE,
  UserPage.JSON_PROPERTY_SIZE,
  UserPage.JSON_PROPERTY_TOTAL_ELEMENTS,
  UserPage.JSON_PROPERTY_TOTAL_PAGES,
  UserPage.JSON_PROPERTY_HAS_NEXT,
  UserPage.JSON_PROPERTY_HAS_PREVIOUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-30T10:49:02.701015900Z[Africa/Sao_Tome]", comments = "Generator version: 7.24.0")
public class UserPage {
  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nonnull
  private List<User> content = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGE = "page";
  @javax.annotation.Nonnull
  private Integer page;

  public static final String JSON_PROPERTY_SIZE = "size";
  @javax.annotation.Nonnull
  private Integer size;

  public static final String JSON_PROPERTY_TOTAL_ELEMENTS = "totalElements";
  @javax.annotation.Nonnull
  private Integer totalElements;

  public static final String JSON_PROPERTY_TOTAL_PAGES = "totalPages";
  @javax.annotation.Nonnull
  private Integer totalPages;

  public static final String JSON_PROPERTY_HAS_NEXT = "hasNext";
  @javax.annotation.Nonnull
  private Boolean hasNext;

  public static final String JSON_PROPERTY_HAS_PREVIOUS = "hasPrevious";
  @javax.annotation.Nonnull
  private Boolean hasPrevious;

  public UserPage() {
  }

  public UserPage content(@javax.annotation.Nonnull List<User> content) {
    
    this.content = content;
    return this;
  }

  public UserPage addContentItem(User contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<User> getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nonnull List<User> content) {
    this.content = content;
  }

  public UserPage page(@javax.annotation.Nonnull Integer page) {
    
    this.page = page;
    return this;
  }

  /**
   * Get page
   * minimum: 0
   * @return page
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getPage() {
    return page;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPage(@javax.annotation.Nonnull Integer page) {
    this.page = page;
  }

  public UserPage size(@javax.annotation.Nonnull Integer size) {
    
    this.size = size;
    return this;
  }

  /**
   * Get size
   * minimum: 1
   * maximum: 100
   * @return size
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIZE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSize() {
    return size;
  }


  @JsonProperty(value = JSON_PROPERTY_SIZE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSize(@javax.annotation.Nonnull Integer size) {
    this.size = size;
  }

  public UserPage totalElements(@javax.annotation.Nonnull Integer totalElements) {
    
    this.totalElements = totalElements;
    return this;
  }

  /**
   * Get totalElements
   * minimum: 0
   * @return totalElements
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ELEMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalElements() {
    return totalElements;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_ELEMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalElements(@javax.annotation.Nonnull Integer totalElements) {
    this.totalElements = totalElements;
  }

  public UserPage totalPages(@javax.annotation.Nonnull Integer totalPages) {
    
    this.totalPages = totalPages;
    return this;
  }

  /**
   * Get totalPages
   * minimum: 0
   * @return totalPages
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL_PAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalPages() {
    return totalPages;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_PAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalPages(@javax.annotation.Nonnull Integer totalPages) {
    this.totalPages = totalPages;
  }

  public UserPage hasNext(@javax.annotation.Nonnull Boolean hasNext) {
    
    this.hasNext = hasNext;
    return this;
  }

  /**
   * Get hasNext
   * @return hasNext
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HAS_NEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getHasNext() {
    return hasNext;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_NEXT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHasNext(@javax.annotation.Nonnull Boolean hasNext) {
    this.hasNext = hasNext;
  }

  public UserPage hasPrevious(@javax.annotation.Nonnull Boolean hasPrevious) {
    
    this.hasPrevious = hasPrevious;
    return this;
  }

  /**
   * Get hasPrevious
   * @return hasPrevious
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HAS_PREVIOUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getHasPrevious() {
    return hasPrevious;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_PREVIOUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHasPrevious(@javax.annotation.Nonnull Boolean hasPrevious) {
    this.hasPrevious = hasPrevious;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPage userPage = (UserPage) o;
    return Objects.equals(this.content, userPage.content) &&
        Objects.equals(this.page, userPage.page) &&
        Objects.equals(this.size, userPage.size) &&
        Objects.equals(this.totalElements, userPage.totalElements) &&
        Objects.equals(this.totalPages, userPage.totalPages) &&
        Objects.equals(this.hasNext, userPage.hasNext) &&
        Objects.equals(this.hasPrevious, userPage.hasPrevious);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, page, size, totalElements, totalPages, hasNext, hasPrevious);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPage {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    totalElements: ").append(toIndentedString(totalElements)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    hasNext: ").append(toIndentedString(hasNext)).append("\n");
    sb.append("    hasPrevious: ").append(toIndentedString(hasPrevious)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

