/*
 * Alumni Platform - User Service API
 * API du service de gestion des utilisateurs.  Ce service gère les profils utilisateurs de la plateforme Alumni. L'authentification et les autorisations sont déléguées à Keycloak.  Les utilisateurs peuvent être : - ADMIN - TEACHER - STUDENT - ALUMNI 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.CreateUserRequest;
import org.openapitools.client.model.ErrorResponse;
import java.util.UUID;
import org.openapitools.client.model.UpdateUserRequest;
import org.openapitools.client.model.User;
import org.openapitools.client.model.UserPage;
import org.openapitools.client.model.UserType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Créer un profil utilisateur
     *
     * Création d&#39;un profil métier après création de l&#39;utilisateur dans Keycloak. 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void createUserTest() {
        CreateUserRequest createUserRequest = null;

        User response = api.createUser(createUserRequest);

        // TODO: test validations
    }
    
    /**
     * Supprimer un utilisateur
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void deleteUserTest() {
        UUID userId = null;

        api.deleteUser(userId);

        // TODO: test validations
    }
    
    /**
     * Récupérer le profil de l&#39;utilisateur connecté
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void getCurrentUserTest() {

        User response = api.getCurrentUser();

        // TODO: test validations
    }
    
    /**
     * Obtenir un utilisateur par ID
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void getUserByIdTest() {
        UUID userId = null;

        User response = api.getUserById(userId);

        // TODO: test validations
    }
    
    /**
     * Rechercher les utilisateurs
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void searchUsersTest() {
        String name = null;
        String email = null;
        UserType type = null;
        Integer page = null;
        Integer size = null;

        UserPage response = api.searchUsers(name, email, type, page, size);

        // TODO: test validations
    }
    
    /**
     * Modifier son propre profil
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void updateCurrentUserTest() {
        UpdateUserRequest updateUserRequest = null;

        User response = api.updateCurrentUser(updateUserRequest);

        // TODO: test validations
    }
    
    /**
     * Modifier un utilisateur
     *
     * 
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void updateUserTest() {
        UUID userId = null;
        UpdateUserRequest updateUserRequest = null;

        User response = api.updateUser(userId, updateUserRequest);

        // TODO: test validations
    }
    
}
